packages:
  - front
  - back
  - packages/*
allowBuilds:
  msgpackr-extract: true
catalog:
  typescript: ^7.0.2
  effect: 4.0.0-rc.109
  oxlint: ^1.78.0
  oxfmt: ^0.63.0
  '@effect/tsgo': ^0.36.5
  oxlint-tsgolint: ^7.0.2001
